version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: estateflow_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: estateflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: estateflow_redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: estateflow_backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/estateflow
      REDIS_URL: redis://redis:6379
      JWT_SECRET: supersecret
      REFRESH_SECRET: refreshsecret
      PORT: 5000

  frontend:
    build: ./frontend
    container_name: estateflow_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api

volumes:
  postgres_data:
